version: '3.7'

services:
  postgres:
    container_name: know-it-all-postgresdb
    image: postgres:10.5
    restart: on-failure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  pgadmin:
    container_name: know-it-all-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: on-failure

volumes:
    postgres:
    pgadmin: